# Generated by Django 3.1.5 on 2021-01-18 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Общий вес отходов')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Расшифровка кода')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('code', models.CharField(max_length=3, verbose_name='Числовой код переработки')),
                ('mark', models.BooleanField(default=True, verbose_name='Возможность вторичной переработки')),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Общий вес отходов')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartPlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_plast', to='mainapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_paper', to='mainapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartGlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_glas', to='mainapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_general', to='mainapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartDanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_danger', to='mainapp.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
    ]
