# Generated by Django 3.1.5 on 2021-01-13 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='CartGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='CartGlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='CartPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='CartPlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('media', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('name', models.CharField(max_length=255, verbose_name='Наимаенование продукта')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Код товара')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('media', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('name', models.CharField(max_length=255, verbose_name='Наимаенование продукта')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('code', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Код переработки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('media', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('name', models.CharField(max_length=255, verbose_name='Наимаенование продукта')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Код товара')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.AddField(
            model_name='cart',
            name='final_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Общий вес отходов'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='final_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=9, verbose_name='Общий вес отходов'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя категории'),
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
        migrations.AddField(
            model_name='milk',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='milk',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки'),
        ),
        migrations.AddField(
            model_name='fulllist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки'),
        ),
        migrations.AddField(
            model_name='cartplast',
            name='products',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_plast', to='mainapp.cart'),
        ),
        migrations.AddField(
            model_name='cartpaper',
            name='products',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_paper', to='mainapp.cart'),
        ),
        migrations.AddField(
            model_name='cartglas',
            name='products',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_glas', to='mainapp.cart'),
        ),
        migrations.AddField(
            model_name='cartgeneral',
            name='products',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_general', to='mainapp.cart'),
        ),
        migrations.AddField(
            model_name='cartdanger',
            name='products',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_danger', to='mainapp.cart'),
        ),
    ]
