# Generated by Django 3.1.5 on 2021-01-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
