# Generated by Django 3.1.5 on 2021-01-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210113_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('media', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('period', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Период разложения (лет)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Вес отходов (кг)')),
                ('name', models.CharField(max_length=255, verbose_name='Наимаенование продукта')),
                ('result', models.CharField(max_length=255, verbose_name='Результат разложения')),
                ('product_code', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Код товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fulllist', verbose_name='Код переработки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
