# Generated by Django 3.1.5 on 2021-01-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_battery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulllist',
            name='category',
        ),
    ]
