# Generated by Django 3.1.5 on 2021-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210113_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulllist',
            name='mark',
            field=models.BooleanField(default=True, verbose_name='Возможность вторичной переработки'),
        ),
    ]
