# Generated by Django 3.1.5 on 2021-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_fulllist_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulllist',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Числовой код переработки'),
        ),
    ]
