# Generated by Django 3.1.5 on 2021-01-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210113_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='milk',
            name='id',
        ),
        migrations.AlterField(
            model_name='battery',
            name='product_code',
            field=models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='product_code',
            field=models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='product_code',
            field=models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False, verbose_name='Код товара'),
        ),
    ]
