# Generated by Django 3.1.5 on 2021-01-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210113_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='product_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='product_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='milk',
            name='product_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
